'use client';

import { Plus_Jakarta_Sans } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import MainNavbar from "@/_mycomponents/navigation/MainNavbar";
import Footer from "@/components/layout/Footer";
import ReduxStoreProvider from "@/_mycomponents/providers/ReduxStoreProvider";
import SessionProvider from "@/_mycomponents/providers/SessionProvider";

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"],
  display: 'swap',
});

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  const pathname = usePathname();
  const isAdminRoute = pathname.startsWith('/admin');

  return (
    <html lang="en">
      <head>
        <title>Music Funeral</title>
        <meta name="Music Funeral" content="Generated by create next app" />
      </head>
      <body className={jakarta.className + " dark:bg-[#111423] min-h-screen flex flex-col"}>
        <ReduxStoreProvider>
          <SessionProvider>
            {!isAdminRoute && <MainNavbar />}
            <main className="flex-grow">{children}</main>
            {!isAdminRoute && <Footer />}
          </SessionProvider>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}